service:
  name: service-10-udagram-app
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless
  region: ap-southeast-2

functions:
  GetOrders:
    handler: src/orders.handler
    events:
      - http:
          method: get
          path: /shop/orders
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
